apiVersion: v1
kind: Pod
metadata:
  name: dapi-test-pod
spec:
  containers:
    - name: test-container
      image: k8s.gcr.io/busybox
      command: [ "/bin/sh", "-c", "env" ]
      # Using configmap as env var
      envFrom:
      - configMapRef:
          name: troubleshoot-utility-cm
      # Secret is being added as a volume
      volumeMounts:
      - name: foo
        mountPath: "/etc/foo"
        readOnly: true
  volumes:
  - name: foo
    secret:
      secretName: troubleshoot-utility-secret 
      optional: false
